framework:
  secret: '%env(APP_SECRET)%'
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
  php_errors:
    log: true
  ide: 'phpstorm://open?file=%%f&line=%%l&/app/>/Users/mrx/Projects/nordcode/time-tracker-app/'