version: '3.7'

volumes:
  app_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/docker/nordcode/time-tracker-app

  db_data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

services:
  web:
    image: nginx
    environment:
      - NGINX_PORT=80
    volumes:
      - app_src:${DKR_APP_DIR}
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - default
    ports:
      - ${DKR_WEB_PORT}:80
    links:
      - app

  app:
    build:
      context: docker/php
      args:
        uid: ${DKR_USER_ID}
        appDir: ${DKR_APP_DIR}
    volumes:
      - app_src:${DKR_APP_DIR}
    networks:
      - default
    expose:
      - 9000
    links:
      - db

  encore:
    build:
      context: docker/encore
      args:
        appDir: ${DKR_APP_DIR}
    hostname: time-tracker-app.local
    volumes:
      - app_src:${DKR_APP_DIR}
    networks:
      - default

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DKR_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.31.0.42
    expose:
      - 3306