version: '3'

volumes:
  app_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .

  db_data:

networks:
  default:
    driver: bridge

services:
  web:
    image: nginx
    environment:
      - NGINX_PORT=80
    volumes:
      - app_src:${DKR_APP_DIR}
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - default
    ports:
      - ${DKR_HTTP_PORT}:80
    links:
      - app

  app:
    build:
      context: docker/php
      args:
        uid: ${DKR_USER_ID}
        appDir: ${DKR_APP_DIR}
    volumes:
      - app_src:${DKR_APP_DIR}
    networks:
      - default
    expose:
      - 9000
    links:
      - db

  fe:
    build:
      context: docker/node
      args:
        appDir: ${DKR_APP_DIR}
    volumes:
      - app_src:${DKR_APP_DIR}
    networks:
      - default

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
    expose:
      - 3306