version: '3.7'

volumes:
  db_data:

networks:
  default:
    driver: bridge

services:
  web:
    image: nginx
    environment:
      - NGINX_PORT=80
    volumes:
      - .:/app
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - default
    ports:
      - 8548:80
    links:
      - app

  app:
    build:
      context: docker/php
      args:
        uid: 999
    volumes:
      - .:/app
    networks:
      - default
    expose:
      - 9000
    links:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
    expose:
      - 3306