parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Component/'
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Tests/'
      - '../src/Resources/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags:
      - 'controller.service_arguments'

  App\Component\Task\ReportGeneratorInterface:
    class: App\Component\Task\Generator\ReportGenerator